using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PrivateClassApp.Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace PrivateClassApp.Data.Config
{
    public class AboutConfig : IEntityTypeConfiguration<About>
    {
        public void Configure(EntityTypeBuilder<About> builder)
        {
            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).ValueGeneratedOnAdd();

            builder.HasData(
                new About { Id = 1, EducationId = 1, ShortInfo = "İstanbul Üniversitesinden mezun olan bir matematik öğretmeni olarak, öğretmenlik kariyerine devam etmek konusunda çok güçlü bir ilgim var.Hem ortaokul hem de lise seviyelerinde ve ayrıca geleneksel sınıf dışındaki etkinliklerde çalışma deneyimim sayesinde, sunabileceğim çok çeşitli bir geçmişe sahibim.", Experience = "İlk matematik öğretmenliği deneyimim, 2 yıl boyunca İstanbul'da ücretli matematik öğretmeni olarak hizmet ettiğim Zihnipaşa İlkokulu oldu. Ayrıca, birkaç yaz boyunca üniversiteye hazırlanan öğrencilere özel dersler vererek çalıştım, referanslarım da belirttiğim öğrencilerin matematik sorularında başarıyı yakalamalarını sağladım." },
                new About { Id = 2, EducationId = 2, ShortInfo = "Lisans ve yüksek lisans eğitimimi Marmara Üniversitesinde tamamladım ve şu anda bir Türk Dili ve Edebiyatı öğretmeniyim. Öğrencilerimi etkileşimli ve eğlenceli derslerle öğrenmeye teşvik ediyorum.", Experience = "5 yıldan fazla bir süredir Türk Dili ve Edebiyatı öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin dil ve yazma becerilerini geliştirmelerine yardımcı olmak için çeşitli etkinlikler ve projeler tasarladım." },
                new About { Id = 3, EducationId = 3, ShortInfo = "Üniversite eğitimimi Boğaziçi Üniversitesi'nde aldım ve İngilizce öğretmenliği kariyerine yüksek lisans yaparak başladım. Öğrencilerimi sınavlara hazırlarken, iletişim becerilerini geliştirirken ve okuma-yazma becerilerini güçlendirirken destekleyen bir öğretmenim.", Experience = "10 yıldan fazla bir süredir İngilizce öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin dil becerilerini geliştirmek için öğretim materyalleri oluşturmak ve onların ilgi alanlarına uygun dersler tasarlamak gibi birçok farklı deneyim yaşadım." },
                 new About { Id = 4, EducationId = 4, ShortInfo = "Boğaziçi Üniversitesinde Matematik bölümünden mezun oldum ve matematik öğretmenliği kariyerime devam ediyorum. Öğrencilerime matematiği anlaşılır ve keyifli hale getirmek için çeşitli öğretim materyalleri kullanıyorum.", Experience = "6 yıldan fazla bir süredir matematik öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin matematik konularını daha iyi anlamalarını sağlamak için özel dersler vermekten, matematik yarışmalarına hazırlamaktan ve matematik kulüpleri oluşturmak gibi farklı deneyimler yaşadım." },
                 new About { Id = 5, EducationId = 5, ShortInfo = "Lisans eğitimimi Ankara Üniversitesinde tamamladım ve Türkçe öğretmenliği yapmaya başladım. Öğrencilerimle etkileşimli dersler yapıyor, onların iletişim becerilerini geliştiriyor ve okuma-yazma becerilerini arttırıyorum.", Experience = "4 yıldan fazla bir süredir Türkçe öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin öğrenme stillerine uygun ders planları hazırlayarak onların Türkçe dilini daha iyi anlamalarına yardımcı oldum. Ayrıca, drama ve hikaye anlatımı gibi farklı etkinliklerle de öğrencilerimin dil becerilerini geliştirmek için çaba harcadım." },
                 new About { Id = 6, EducationId = 6, ShortInfo = "Müzik eğitimimi Hacettepe Üniversitesinde tamamladım ve şu anda müzik öğretmenliği yapıyorum. Öğrencilerimin müzikal becerilerini geliştirirken, aynı zamanda onların özgüvenlerini arttırmaya çalışıyorum.", Experience = "8 yıldan fazla bir süredir Ankara'da müzik öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin müzikal yeteneklerini geliştirmek için onları farklı enstrümanlarla tanıştırdım ve müzik etkinlikleri organize ettim. Ayrıca, müzik kulüpleri oluşturarak öğrencilerimin müzikle ilgili tutkularını desteklemeye çalıştım." },
                 new About { Id = 7, EducationId = 7, ShortInfo = "Lisans ve yüksek lisans eğitimimi Ankara Üniversitesinde tamamladım ve Türk Dili ve Edebiyatı öğretmenliği yapıyorum. Öğrencilerimin okuma ve yazma becerilerini geliştirirken, Türk edebiyatını sevdirmek için çaba harcıyorum.", Experience = "9 yıldan fazla bir süredir Türk Dili ve Edebiyatı öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin dil becerilerini geliştirmek için çeşitli ders materyalleri oluşturdum ve öğrencilerimin ilgi alanlarına uygun kitaplar seçmelerine yardımcı oldum. Ayrıca, tiyatro ve edebiyat kulüpleri oluşturarak öğrencilerimin Türk edebiyatına olan ilgisini arttırmaya çalıştım." },
                 new About { Id = 8, EducationId = 8, ShortInfo = "İngilizce öğretmenliği kariyerime lisans eğitimimden sonra başladım ve şu anda ortaokul ve lise öğrencilerine İngilizce dersleri veriyorum. Öğrencilerimle interaktif dersler yaparak, onların dil becerilerini geliştirmeye çalışıyorum.", Experience = "7 yıldan fazla bir süredir İngilizce öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin sınavlara hazırlanmalarına ve konuşma becerilerini geliştirmelerine yardımcı oldum. Ayrıca, dil öğrenme teknikleri konusunda kendimi sürekli geliştirerek öğrencilerime farklı öğrenme stillerine uygun dersler sunmaya çalışıyorum. Ayrıca, uluslararası öğrencilerle çalışarak, kültürlerarası iletişim becerilerini de geliştirmelerine yardımcı oldum."},
                 new About { Id = 9, EducationId = 9, ShortInfo = "Fen bilimleri öğretmenliği yapmaktayım ve öğrencilerimin bilimsel düşünme becerilerini geliştirmeye odaklanıyorum. Derslerimde öğrencilerimin aktif katılımını teşvik ediyorum ve onları problem çözme ve araştırma yapmaya teşvik ediyorum.", Experience = "10 yıldan fazla bir süredir fen bilimleri öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin laboratuvar deneyleri yapmalarına ve araştırmalar yapmalarına olanak sağladım. Ayrıca, bilim kulüpleri oluşturarak öğrencilerimin bilimle ilgili tutkularını desteklemeye çalıştım." },
                 new About { Id = 10, EducationId = 10, ShortInfo = "Sosyal bilimler öğretmeni olarak öğrencilerimi tarihin önemini anlamaları ve dünya olayları hakkında daha bilinçli olmaları için teşvik ediyorum. Sınıfta tartışma ve analiz yapmayı teşvik ederek, öğrencilerimin eleştirel düşünme becerilerini geliştirmeye çalışıyorum.", Experience = "5 yıldan fazla bir süredir sosyal bilimler öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin tarih, coğrafya ve sosyal bilimler konularında ilerlemelerini sağladım. Ayrıca, öğrencilerimin araştırma yapma ve sunum yapma becerilerini geliştirmelerine yardımcı oldum." },
                 new About { Id = 11, EducationId = 11, ShortInfo = "Psikoloji öğretmeni olarak öğrencilerime akademik ve kişisel gelişimlerinde yardımcı olmaya çalışıyorum. Öğrencilerimle bireysel ve grup terapileri yaparak, onların duygusal ihtiyaçlarını karşılamaya çalışıyorum.", Experience = "3 yıldan fazla bir süredir psikoloji öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin duygusal ve sosyal ihtiyaçlarını karşılamak için terapi oturumları düzenledim. Ayrıca, öğrencilerimin stres yönetimi ve özgüvenlerini arttırmalarına yardımcı oldum." },
                 new About { Id = 12, EducationId = 12, ShortInfo = "Müzik öğretmeni olarak, öğrencilerimin müzikal yeteneklerini keşfetmelerine ve geliştirmelerine yardımcı oluyorum. Farklı enstrümanlar ve müzik türleri hakkında bilgi sahibi olduğum için öğrencilerime geniş bir perspektif sunabiliyorum.", Experience = "8 yıldan fazla bir süredir müzik öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin müzikal yeteneklerini geliştirmelerine yardımcı olmak için özel dersler verdim ve müzik gruplarına liderlik ettim. Ayrıca, okul orkestrası ve korosu gibi gruplarla birlikte çalışarak, öğrencilerimin işbirliği ve takım çalışması becerilerini geliştirmelerine yardımcı oldum." },
                 new About { Id = 13, EducationId = 13, ShortInfo = "Biyoloji öğretmeni olarak, öğrencilerimin doğal dünya hakkında meraklarını ve ilgilerini uyandırmaya çalışıyorum. Biyolojik süreçleri anlamalarına ve yaşamlarının bir parçası olan canlıların çeşitliliği hakkında bilgi sahibi olmalarına yardımcı oluyorum.", Experience = "10 yıldan fazla bir süredir biyoloji öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin biyoloji konularında başarılı olmaları için özel dersler verdim ve biyoloji kulüpleri kurarak öğrencilerimin ilgisini arttırdım. Ayrıca, biyolojik araştırmalar yaptırdığım öğrenciler yetiştirerek bilimsel yöntemler ve araştırma becerilerini geliştirdim." },
                 new About { Id = 14, EducationId = 14, ShortInfo = "Kimya öğretmeni olarak, öğrencilerimin kimyayı anlamalarına ve uygulamalarını görmelerine yardımcı oluyorum. Farklı kimya konuları hakkında bilgi sahibi olduğum için öğrencilerime geniş bir perspektif sunabiliyorum.", Experience = "7 yıldan fazla bir süredir kimya öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin kimya konularını anlamalarına yardımcı olmak için özel dersler verdim ve kimya kulüpleri kurarak öğrencilerimin ilgisini arttırdım. Ayrıca, okul laboratuvarlarında araştırmalar yaptırdığım öğrenciler yetiştirerek bilimsel yöntemler ve araştırma becerilerini geliştirdim." },
                 new About { Id = 15, EducationId = 15, ShortInfo = "Fizik öğretmeni olarak, öğrencilerimin fiziksel dünyayı anlamalarına ve uygulamalarını görmelerine yardımcı oluyorum. Farklı fizik konuları hakkında bilgi sahibi olduğum için öğrencilerime geniş bir perspektif sunabiliyorum.", Experience = "5 yıldan fazla bir süredir fizik öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin fizik konularını anlamalarına yardımcı olmak için özel dersler verdim ve fizik kulüpleri kurarak öğrencilerimin ilgisini arttırdım. Ayrıca, okul laboratuvarlarında araştırmalar yaptırdığım öğrenciler yetiştirerek bilimsel yöntemler ve araştırma becerilerini geliştirdim. Ayrıca, öğrencilerimin ilgisini çekmek için farklı fizik deneyleri yaparak, fiziksel fenomenleri uygulamalı olarak göstermeye çalışıyorum."},
                 new About { Id = 16, EducationId = 16, ShortInfo = "Organik kimya öğretmeni olarak, öğrencilerimin organik bileşikleri anlamalarına ve uygulamalarını görmelerine yardımcı oluyorum. Organik kimya konularında derin bir bilgiye sahibim ve öğrencilerime bu alanda geniş bir perspektif sunuyorum.", Experience = "8 yıldan fazla bir süredir organik kimya öğretmenliği yapıyorum. Bu süre zarfında, öğrencilerimin organik kimya konularını anlamalarına yardımcı olmak için özel dersler verdim ve organik kimya kulüpleri kurarak öğrencilerimin ilgisini arttırdım. Ayrıca, okul laboratuvarlarında araştırmalar yaptırdığım öğrenciler yetiştirerek bilimsel yöntemler ve araştırma becerilerini geliştirdim." }
            );
        }
    }
}
